### ISSUE TITLE
Error running with lensfun v0.3.0

### ISSUE THREAD

**Issue by raghavaggsss** [letmaik/lensfunpy#54]
`Traceback (most recent call last):
  File "test_lensfunpy.py", line 2, in <module>
    import lensfunpy
  File "/usr/local/lib/python3.8/dist-packages/lensfunpy/__init__.py", line 7, in <module>
    import lensfunpy._lensfun
ImportError: /usr/local/lib/python3.8/dist-packages/lensfunpy/_lensfun.cpython-38-x86_64-linux-gnu.so: undefined symbol: lf_modifier_new`

**Comment by letmaik** [comment]
Please use the provided wheels, no support is provided for building from source.
